{
	"version": 1664565034,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/tiledbackground.png",
		"images/navenumeros-sheet0.png",
		"images/navenumeros-sheet1.png",
		"images/btncomprobar-sheet0.png",
		"images/btnborrar-sheet0.png",
		"images/textocorrecto-sheet0.png",
		"images/particles.png",
		"images/tiledbackground2.png",
		"images/borde.png",
		"images/hulk-sheet0.png",
		"images/hulk-sheet1.png",
		"images/hulk-sheet2.png",
		"images/suelonavepahulk-sheet0.png",
		"images/aplasta-sheet0.png",
		"images/edificio_01-sheet0.png",
		"images/edificios_02.png",
		"images/edificiosfondo-sheet0.png",
		"images/nubes_01-sheet0.png",
		"images/textgameover-sheet0.png",
		"images/hulkcaratula-sheet0.png",
		"images/hulkcaratulaaplasta-sheet0.png",
		"images/btncomenzar-sheet0.png",
		"images/ohcuerpo-sheet0.png",
		"images/ohcuerpo-sheet1.png",
		"images/ohcuerpo-sheet2.png",
		"images/armpointing-sheet0.png",
		"images/ohcabeza-sheet0.png",
		"images/ohcabeza-sheet1.png",
		"images/ohcabeza-sheet2.png",
		"images/leftarm-sheet0.png",
		"images/ohboca-sheet0.png",
		"images/ohboca-sheet1.png",
		"images/ohboca-sheet2.png",
		"images/armopened-sheet0.png",
		"images/armopened-sheet1.png",
		"images/armfront-sheet0.png",
		"images/armfront-sheet1.png",
		"images/estrellasgolpe-sheet0.png",
		"images/borde2.png",
		"images/btnborrar_02-sheet0.png",
		"images/hit_oh_head-sheet0.png",
		"images/controlcruz-sheet0.png",
		"images/controlup-sheet0.png",
		"images/controlleft-sheet0.png",
		"images/controlright-sheet0.png",
		"images/controldown-sheet0.png",
		"images/controcruzcentrol-sheet0.png",
		"images/controlaplasta-sheet0.png",
		"images/arbol-sheet0.png",
		"images/fondocontroles.png",
		"images/ohcaratula-sheet0.png",
		"media/salto.m4a",
		"media/salto.ogg",
		"media/rock-smash-6304_wav_.m4a",
		"media/rock-smash-6304_wav_.ogg",
		"media/correct.m4a",
		"media/correct.ogg",
		"media/jeje.m4a",
		"media/jeje.ogg",
		"media/eso es.m4a",
		"media/eso es.ogg",
		"media/matematico.m4a",
		"media/matematico.ogg",
		"media/poder.m4a",
		"media/poder.ogg",
		"media/hulk aplasta.m4a",
		"media/hulk aplasta.ogg",
		"media/game_over_02 (famale).m4a",
		"media/game_over_02 (famale).ogg",
		"media/hulk no me respeta.m4a",
		"media/hulk no me respeta.ogg",
		"media/ayayay.m4a",
		"media/ayayay.ogg",
		"media/tienes.m4a",
		"media/tienes.ogg",
		"media/20. energy blast (bajito).m4a",
		"media/20. energy blast (bajito).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}